<?php
	abstract class RegCodes {
		const ILLEGAL_PASSWORD = "ILLEGAL_PASSWORD";
		const ILLEGAL_USERNAME = "ILLEGAL_USERNAME";
		const USED_USERNAME = "USED_USERNAME";
		const REGISTER_SUCCESS = "REGISTER_SUCCESS";
	}
//echo "RegCodes::ILLEGAL_PASSWORD = " . Re
//gCodes::ILLEGAL_PASSWORD;
?>
